#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "D:/doc/ck/PhD/courses/CPSC 427 - Spring 2025 (W2)/assignments/A1/A1_template_tower_defense/"
